name: tscansdk
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - flask==3.1.0
    - flask-socketio==5.5.1
    - opencv-python==4.11.0.86
    - numpy==2.2.3
    - python-engineio==4.11.2
    - python-socketio==5.12.1
    - werkzeug==3.1.0
    - Jinja2==3.1.2
    - click==8.1.7
    - itsdangerous==2.2.0
    - bidict==0.22.1
    - simple-websocket==1.1.0 